spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: orders_service_route
              uri: http://${ORDERS_URI:localhost:8081}
              predicates:
                - Path=/orders/**
              filters:
                - StripPrefix=1

            - id: payments_service_route
              uri: http://${PAYMENTS_URI:localhost:8082}
              predicates:
                - Path=/payments/**
              filters:
                - StripPrefix=1